In [1]:
import pandas as pd
import matplotlib
import numpy as np

In [59]:
c_dat = pd.read_csv('C_token1.csv')
c_dat_2 = pd.read_csv('C_token2.csv')
c_diff = pd.read_csv('C_diff_ratio')

In [60]:
def format_df(df):
    df.index = df["Unnamed: 0"]
    df.rename_axis(index="uuid_row", columns="uuid_col", inplace=True)
    df.drop(columns="Unnamed: 0", inplace=True)

In [61]:
format_df(c_dat)
format_df(c_dat_2)
format_df(c_diff)

In [62]:
c_diff.head()

uuid_col,575097,575099,575100,575101,575102,575103,575105,575106,575107,575108,...,575135,575137,575138,575139,575140,575142,575143,575144,575146,575148
uuid_row,,,,,,,,,,,,,,,,,,,,,
575097,0.000000,0.193329,0.228362,0.172249,0.101371,0.174025,0.207304,0.192729,0.205181,0.199370,...,0.235205,0.226337,0.465708,0.282334,0.098444,0.264258,0.113235,0.163895,0.182019,0.157148
575099,0.263989,0.000000,0.165134,0.043237,0.172360,0.074148,0.063221,0.061012,0.144127,0.135501,...,0.171347,0.163504,0.411189,0.203672,0.169069,0.204416,0.074893,0.097422,0.038523,0.216116
575100,0.183539,0.093645,0.000000,0.062904,0.085438,0.079242,0.068251,0.065884,0.153261,0.205040,...,0.038547,0.050066,0.344062,0.101263,0.081960,0.105892,0.089609,0.163427,0.066437,0.131167
575101,0.140964,0.043237,0.132271,0.000000,0.033134,0.004080,0.031097,0.036442,0.122527,0.073953,...,0.133277,0.136326,0.310238,0.053666,0.029647,0.055947,0.039106,0.026524,0.017164,0.088101
575102,0.099928,0.167702,0.156145,0.044711,0.000000,0.047486,0.063225,0.057781,0.096534,0.127623,...,0.165916,0.154815,0.423536,0.209929,0.003920,0.209881,0.011714,0.086948,0.047962,0.064998